// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/dstgo/tracker/internal/api/user"
	"github.com/dstgo/tracker/internal/data"
	user2 "github.com/dstgo/tracker/internal/handler/user"
	"github.com/dstgo/tracker/pkg/ginx"
)

import (
	_ "github.com/dstgo/tracker/internal/api/docs"
)

// Injectors from wire.go:

//go:generate wire gen
func setupOpenAPIRouter(open *ginx.RouterGroup, datasource *data.DataSource) Router {
	infoLogic := user.NewInfoLogic(datasource)
	userInfo := user2.NewUserInfo(datasource)
	infoApi := user.NewInfoApi(infoLogic, userInfo)
	api := user.API{
		Info: infoApi,
	}
	apiRouter := user.SetupRouter(open, api)
	router := Router{
		User: apiRouter,
	}
	return router
}
