basePath: /open/v1
definitions:
  auth.APIKey:
    properties:
      expiredAt:
        type: integer
      key:
        type: string
      name:
        type: string
    type: object
  types.Response:
    properties:
      code:
        example: 2000
        type: integer
      data: {}
      err:
        type: string
      msg:
        example: operation success
        type: string
    type: object
info:
  contact:
    name: dstgo
    url: https://github.com/dstgo
  description: open api documentation, to access these open api, you need to add apikey
    in query param named "key"
  license:
    name: MIT LICENSE
    url: https://mit-license.org/
  title: App Open API Documentation
  version: v1.0.0
paths:
  /info:
    get:
      consumes:
      - application/json
      description: get the key info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.APIKey'
              type: object
      security:
      - ApiKeyAuth: []
      summary: KeyInfo
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: query
    name: key
    type: apiKey
swagger: "2.0"
