[route]
# 系统路由
sys.group = "系统"
sys.ping = "Ping测试"
sys.pong = "Pong测试"
# 认证路由
auth.group = "认证"
auth.login = "用户登录"
auth.register = "用户注册"
auth.logout = "用户登出"
auth.forgotPasswd = "用户找回密码"
auth.refresh = "刷新令牌"
# 用户个人路由
user.profile.group = "个人信息"
user.profile.info = "查询信息"
user.profile.save = "更新信息"
# 用户管理路由
user.admin.group = "用户管理"
user.admin.info = "查询用户信息"
user.admin.list = "查询用户列表"
user.admin.create = "创建用户"
user.admin.save = "更新用户"
user.admin.remove = "删除用户"
# 邮箱路由
email.group = "邮箱"
email.code = "发送验证码邮件"
email.notify = "发送通知邮件"
# 角色路由
role.group = "角色"
role.list = "获取角色列表"
role.perms = "获取角色权限列表"
role.creae = "创建角色"
role.update = "更新角色"
role.grant = "角色授权"
role.remove = "删除角色"
# 权限路由
perm.group = "权限"
perm.list = "获取权限列表"
perm.create = "创建权限"
perm.update = "更新权限"
perm.remove = "删除权限"
# APIKey路由
key.group = "OpenAPI"
key.list = "获取key列表"
key.create = "创建key"
key.remove = "删除key"



# 数据校验部分
[validate]
isnil = "必须是空值"
isempty = "必须是默认值"
required = "是必需值，不能为空"
empty = "不能为零值"
notnil = "不能为空"
oneof = "必须是[%v]几个值其中之一"
notoneof = "不能是[%v]几个值其中之一"
gt = "必须大于%v"
gte = "必须大于等于%v"
lt = "必须小于%v"
lte = "必须小于等于%v"
eq = "必须等于%v"
match = "必须匹配正则表达式%v"
multiple = "必须是%v的倍数"
date = "必须是有效的日期格式"

[validate.length]
range = "长度必须位于%v到%v之间"
max = "长度必须小于等于%v"
min = "长度必须大于等于%v"
eq = "长度必须等于%v"

[validate.string]
email = "必须是有效的邮箱格式"
url = "必须是有效的URL"
requrl = "必须是有效的请求URL"
requri = "必须是有效的请求URI"
alpha = "只能包含英文字母"
digit = "只能包含数字"
alphanum = "只能包含英文字母和数字"
unicode = "只能包含unicode字母字符"
unicodenum = "只能包含unicode十进制数"
unicodeletternum = "只能包含unicode字母和数字"
unicodenumch = "只能包含unicode数字字符"
lower = "必须是小写字符串"
upper = "必须是大写字符串"
hex = "必须是十六进制数"
hexcolor = "必须是十六进制颜色"
rgb = "必须是RGB格式颜色代码"
int = "必须是整型数字"
float = "必须是浮点型数字"
uuidv3 = "必须是一个有效的UUID v3"
uuidv4 = "必须是一个有效的UUID v4"
uuidv5 = "必须是一个有效的UUID v5"
uuid = "必须是一个有效的UUID"
creditcard = "必须是一个有效的信用卡号"
isbn10 = "必须符合ISBN-10的规范"
isbn13 = "必须符合ISBN-13的规范"
isbn = "必须符合ISBN的规范"
json = "必须符合JSON格式"
ascii = "只能包含ASCII字符"
printable = "只能包含可打印的字符"
multibyte = "只能包含多字节的字符"
fullwidth = "只能包含全角字符"
halfwidth = "只能包含半角字符"
fullhalfwidth = "只能包含全角和半角字符"
base64 = "必须是Base64编码"
base64uri = "必须是base64编码的数据URI"
e164 = "必须是有效的E164数字"
2code = "必须是有效的两字母国家代码"
3code = "必须是三字母国家代码"
iso4217code = "必须是有效的ISO4217货币代码"
dial = "必须是有效的Dial字符串"
mac = "必须是有效的MAC地址"
ip = "必须是有效的IP地址"
ipv4 = "必须是有效的IPv4地址"
ipv6 = "必须是有效的IPv6地址"
subdomain = "必须是有效的子域名"
domain = "必须是有效的域名"
dns = "必须是有效的DNS名称"
host = "必须是有效的主机名"
port = "必须是有效的端口"
mongoid = "必须是有效的十六进制编码的MongoDB ObjectId"
latitude = "必须是有效纬度"
longitude = "必须是有效经度"
ssn = "必须是有效的SSN代码"
version = "必须是有效语义版本"

# 自定义校验规则
[rule]
perm.object = "权限主体只能由字母数字，正斜杠和下划线组成"


# 字段名称
[field]
name = "名称"
email = "邮箱"
username = "用户名"
password = "密码"
phone = "手机号码"
age = "年龄"
userid = "用户标识符"
uuid = "用户唯一标识符"
code = "验证码"
page = "页数"
pagesize = "页容量"
perm.name = "权限名称"
perm.id = "权限标识符"
perm.list = "权限列表"
perm.object = "权限主体"
perm.action = "行为限制"
perm.tag = "权限标签"
role.id = "角色标识符"
role.name = "角色名称"
role.code = "角色代码"
role.list = "角色列表"
token.access = "认证令牌"
token.refresh = "刷新令牌"

# 错误信息部分
[op]
ok = "操作成功"
fail = "操作失败"
query.ok = "查询成功"
query.fail = "查询失败"
create.ok = "创建成功"
create.fail = "创建失败"
update.ok = "更新成功"
update.fail = "更新失败"
delete.ok = "删除成功"
delete.fail = "删除失败"

[err]
unknown = "未知错误"
badparams = "参数校验未通过"
forbidden = "无权访问"
unauthorized = "认证未通过"
database = "数据库错误"
filesystem = "文件IO错误"
network = "网络错误"
program = "程序错误"
notfound = "访问的资源不存在"
methodnotallowed = "不支持的HTTP方法"
internal = "服务器内部错误"

[email]
code.subject = "来自dstgo的验证码邮件，请及时查看"
code.expired = "验证码已过期"
sendFail = "邮件发送失败"
sendOk = "邮件已发送"

[jwt]
parsed.failed = "用户认证失败，请尝试重新登录"
issue.failed = "凭证签发失败"
expired = "用户凭证失效，请重新登录"
refresh = "用户凭证过期，请重新申请"
invalid = "无效的凭证"
redundant = "凭证无需更新"

[key]
invalid = "无效的密钥"
noperm = "密钥权限不足"
nopexp = "无效的过期时间"

[auth]
loginFail = "登录失败"
loginOk = "登录成功"
registerFail = "注册失败"
registerOk = "注册成功"
logoutFail = "退出登录失败"
logoutOk = "退出登录成功"
changePasswdFail = "密码修改失败"
changePasswdOk = "密码修改成功"
refresh.failed = "令牌刷新失败"
refresh.ok = "令牌刷新成功"

[user]
notfound = "用户不存在"
alreadyExist = "用户已存在"
wrongPassword = "密码错误"

[role]
notfound = "角色不存在"
codeConflict = "已存在相同的角色代码"
invalidList = "无限的角色列表"

[perm]
notfound = "不存在的权限"
invalidList = "无效的权限列表"
conflict = "已存在相同的权限定义"
noPerm = "当前用户角色没有权限访问"

