# app configuration
app:
  # if swagger api doc enable, the apidoc can visit on http://http.address/swagger/index.html
  swagger: true
  # If openapi is enabled, the outside world can use the key to interact with the app through openapi
  openapi: false
  # http server configuration
  http:
    # http bind address hots:port
    address: 127.0.0.1:8080
    # http request read timeout
    readTimeout: 60s
    # http response write timeout
    writeTimeout: 60s
    # header read timeout
    readHeaderTimeout: 10s
    # keep-alive timeout
    idleTimeout: 300s
    # multipart max size by bytes
    multipartMemory: 52428800
    # max header size by bytes
    maxHeaderBytes: 3145728
    # tls enable
    tls:
      # enable
      enable: false
      # tls cert file
      cert: xxx
      # tls pem file
      pem: xxx
    # cross-origin configuration
    cors:
      enable: true
      # allow origin
      allowOrigins:
        - http://localhost
        - http://127.0.0.1
      # allows methods
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      # allow headers
      allowHeaders:
        - Accept-Language
        - Authorization
        - Origin
      # exposed headers
      exposedHeaders:
        - Date
        - Content-Language
        - Content-Type
        - Content-Length
      # http prefilight cached time by seconds
      maxAge: 600
      # cookies credentials enabled, but the project's authentication way is JWT,so no need to set this value
      allowCredentials: false

  # rpc client configuration
  rpc:

# log configuration
log:
  # logger entry format: text | json
  format: text
  # min level should be one of [fatal panic error warn info debug trace]
  level: debug
  # a log entry whose level below or equal info will be output specified dir path
  infoLog: /etc/dstgo/log/info.log
  # a log entry whose level above info will be output specified dir path
  errorLog: /etc/dstgo/log/error.log

# i18n support
locale:
  # default language
  lang: zh-CN
  # specified dir where the language file stored in
  # language file extension should be supported by viper
  dir: /etc/dstgo/lang

# data source
data:
  # database configuration
  database:
    # driver type which should be supported by gorm
    driver: mysql
    # db network
    network: tcp
    # db address
    addr: 192.168.48.138:3306
    # db user
    user: root
    # db auth
    pswd: 123456
    # db connect params
    params: dstgo?charset=utf8mb4&parseTime=True&loc=Local
    # max open connections
    maxOpenCons: 200
    # max idle connections
    maxIdleCons: 20
    # conns max idle time
    maxIdleTime: 600s
    # conns max lifetime
    maxLifeTime: 3600s


  # redis configuration
  redis:
    # redis server address host:port
    addr: 192.168.48.138:6379
    # redis server auth password
    auth: 123456
    # times of max retry
    retry: 5
    # min idle connections
    minIdleConns: 10
    # limit read timeout by ms
    readTimeout: 5000ms
    # limit write timeout by ms
    writeTimeout: 5000ms

# jwt configuration
jwt:
  # jwt sign
  sig: dstgo
  # jwt issuer
  isu: dstgo
  # jwt expire time
  exp: 4h
  # refresh jwt expire time
  rexp: 108h
  # access token delay expiration time
  delay: 10m

email:
  # email host
  host: smtp.qq.com
  port: 587
  user: dstgowilson@foxmail.com
  password: xxxxxx
  # send mail timeout
  timeout: 1m
  # max pool size
  maxPoolSize: 20
  # email auth code expiration time by minutes
  exp: 5

dst:
  # steam web api key
  steamKey: xxxxxxxx
  # klei private token
  kleiToken: xxxxxxxx